### PR TITLE
Add defaults for Debian, Redhat and Suse family

### PR DESCRIPTION
**Pull request by BillKalaitzis**
- Introduce OS-specific defaults for the most popular Linux Families.
- Adjust the data lookup strategy in order to accommodate for OS-specific defaults

### CODE REVIEW

**Comment by trefzer** [comment]
First thanks for the contribution ;)
Question: could you make a remark (eg. in the Readme or in the os specific yaml file) what you achieve with these defaults (are these the os defaults, what 'sort' of mailserver (relay, main server) will you get with these defaults ?

Can you update the metadata.json file to reflect the changes (eg add SLES, add versions information for Ubuntu)

And last your current suggestion will alter all current usage of the module, since we are using hash merges for the parameters. I think this is not a good idea. We should better use the [default_hierarchy](https://puppet.com/docs/puppet/5.5/hiera_config_yaml_5.html#the-default_hierarchy-key)  in hiera.yaml to avoid these. With this we will achieve good defaults for first users, but should not alter existing installations if they already set some parameters.

**Comment by du5tball** [comment]
Hello, the current module is written with Debian defaults in mind, which doesn't work on RHEL/CentOS, or SLES (for example Debian uses chroot everywhere, RedHat doesn't). All the PR does is add defaults for SLES and RedHat / CentOS, but for that to work the data under common has to be moved as well, since at least the services have different defaults depending on the os family.

I'm not so sure about adding a default_hierarchy. First of all because the module currently doesn't use it either and second because it would most likely introduce actual breakage. The module currently defines all services and if one changes a parameter in the module's current state, only that parameter gets changed. If the default_hierarchy was used and a user wanted to change just one service parameter, the whole module data layer would be removed (both master.cf and main.cf, unless separate default layers for each are defined), leaving them with only the reconfigured service.

Of course, feel free to correct me if I'm missing something. We'll make the other requested modifications (metadata and readme) when we've found common ground for merging.

**Comment by du5tball** [comment]
@trefzer have you had the chance of thinking about the default_hierarchy yet?

**Comment by trefzer** [comment]
Sorry it took such long, but times are busy !
To be honest, I do not know what the best way to go is. Currently if the module is used, it creates a minimal configuration, which is indeed not usable, but can be extended easily (usable for real mail server as well as for satelite system which just relay). But indeed it always needs configuration.
Your patch adds defaults, which are equal to the packaged version per OS. This gives a functional system, but makes very complicated to create a stripped down version eg. for satellite systems (which eg. do not need maildrop, uucp, ifmail, bsmtp, mailman service).
The default_hierarchy has indeed the drawback to need a full configuration to change which is also not ideal.

I'm currently thinking to have another approach, which I will explain with the postfix::services parameter, but could also be used for postfix::parameters:

What if we create a hash postfix::services_osdefaults  and a boolean use_services_os_defaults.
if use_services_os_defaults is true, we merge postfix::services and postfix_services_osdefaults which then results in the complete hash per operating system. If use_services_os_defaults is false, we can still achive the minimal, not functioning version.

This also has the advantage, that we can implement it without a new major version by just setting the boolean to false (but I indeed think we should set it to true in a second step and increate the major version.)

What do you think about that approach ? (I'm also not 100% convinced  if the idea is good, but it seems to be the way to achive both goals).

**Comment by du5tball** [comment]
After some internal discussion it's been decided that our PR was well intended, but not well done. This can be closed :)

**Comment by trefzer** [comment]
Uh ! I did not expect that answer !
Question: is  BillKalaitzis same company as du5tball ?

Second, can you provide some more details about that ?

**Comment by du5tball** [comment]
Yes, we are (or rather were, when this PR was opened) in the same company. I'm still there. I'm mainly responsible for building and maintaining puppet servers, but have barely anything to do with mail. Our operations want to switch some systems from exim to postfix, so the quest to search for a module began, and me in my naivete thought "everything should at least have the OS defaults" as is the case with a lot of other modules, the thought of smarthosts not even crossing my mind.

After having a few talks with operations  (which admittedly should've happened earlier), they've tested the module and came to the conclusion that it works with the default settings in ~99% of the cases and the efforts of adding the defaults to everything was wasted, since most of the services would be turned off for smarthosts anyways.

**Comment by BillKalaitzis** [comment]
> Uh ! I did not expect that answer !
> Question: is BillKalaitzis same company as du5tball ?
> 
> Second, can you provide some more details about that ?

Hello trefzer, 

I can verify du5tball's claims :) 
We used to work for the same company when this PR was launched.

I'll proceed with closing this as requested.
Thanks everybody for your time!

**Pull request closed without merging**
